name: Release

on:
  push:
    tags:
      - 'v*'  # Aciona a ação quando uma tag começar com "v"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # ou qualquer versão que você esteja usando

      - name: Install dependencies
        run: npm install

      - name: Build and publish release
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
